language: python
dist: bionic
sudo: false
cache: pip
language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=check PYTEST_NO_COVERAGE=1 PYTEST_ADDOPTS=""
    - python: 3.7
      env: TOXENV=mypy  PYTEST_NO_COVERAGE=1 PYTEST_ADDOPTS=""
    - python: 3.6
      env: TOXENV=py36 PYTEST_ADDOPTS=""
    - python: 3.7
      env: TOXENV=py37 PYTEST_ADDOPTS=""
    - python: 3.8
      env: TOXENV=py38 PYTEST_ADDOPTS=""
    - python: pypy3.6-7.2.0
      env: TOXENV=pypy3 PYTEST_ADDOPTS=""

install:
  - pip install tox-travis codecov coveralls

script: tox

after_success:
  - |
    if [[ "$PYTEST_NO_COVERAGE" != 1 ]]; then
      coverage combine
      coverage xml --ignore-errors
      coverage report -m --ignore-errors
      codecov --required -X gcov pycov search -f coverage.xml --flags ${TOXENV//-/ } linux || true
      coveralls
    fi
